Caritas/urls.py
from django.contrib import admin
from django.urls import path, include
from registrarAyudante.views import registro
from verAyudantesRegistrados.views import ver_ayudantes, confirmar_eliminar_ayudante
from editarPerfilAdministrador.views import editar_perfil
from buscarArticulo.views import buscar_articulos
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from app import views
from . import views as viewsInicio
from cargarArticulo import views as cargarArticuloViews
from verArticulosPendientes.views import mostrar_articulos_pendientes 
from verArticulosPendientes.views import mostrarArticulosPendientesPropios
from controlarPublicacion import views as controlar_publicacionViews
from autenticacionIntercambiador import views as autenticacion_views
from verPerfilPropio import views as perfil_views
from verDetalleDeArticulo import views as viewsDetalle
from verOtroUsuario import views as other_profile_views
from eliminarCuenta import views as eliminar_cuenta_views
from verArticulosPropios.views import ver_articulos
from bloquearUsuario.views import bloquear_usuario 
from bloquearUsuario.views import lista_usuarios
from needList import views as needListViews
from solicitarIntercambio.views import solicitar_intercambio
from controlarIntercambio.views import controlar_intercambio


from . import pendienteBloqueo

urlpatterns = [
    path('', RedirectView.as_view(url='Inicio/', permanent=True)),
    path('admin/', admin.site.urls),
    path('registrar/', registro,name = 'registro'),
    path('editarPerfil/<int:usuario_id>/', editar_perfil,name = 'editarPerfilAdmin'),
    path('Inicio/', viewsInicio.hello, name='inicio'),
    path('register/', views.registro, name='register'),
    path('cargarArticulo/', cargarArticuloViews.cargar_articulo, name='cargar_articulo'),
    path('articulos_pendientes', mostrar_articulos_pendientes, name='mostrar_articulos_pendientes'),
    path('controlar_publicacion/<int:articulo_id>/', controlar_publicacionViews.controlar_publicacion, name='controlar_articulo'),
 path('desaprobar/<int:articulo_id>/', controlar_publicacionViews.desaprobar_articulo, name="desaprobar"),
   path('aprobar/<int:articulo_id>/', controlar_publicacionViews.aprobar_articulo, name="aprobar"),
   path('mostrar_por_categoria/', viewsInicio.mostrarPorCategoria, name='mostrar_por_categoria'),
  path('register/', views.registro, name='register'),
  path('login/', autenticacion_views.login_view, name='login'),  # Incluye las URLs de autenticacionIntercambiador
  path('perfil_propio/', perfil_views.view_profile, name='perfil_propio'),  
  path('', include('ayudanteAuth.urls')),
  path('', include('chngPassRequest.urls')),
  path('', include('changePassword.urls')),
  path('', include('logout.urls')),
  path('', include('crearFilial.urls')),
  path('', include('listarFiliales.urls')),
  path('', include('eliminarFilial.urls')),
  path('', include('verIntercambiadores.urls')),
  path('confirmar_eliminar_cuenta/', viewsInicio.confirmar_eliminar_cuenta, name='confirmar_eliminar_cuenta'), 
  path('menuPrincipal/', viewsInicio.mostrar, name='menuPrincipal'),# Incluye las URLs de verPerfilPropio
  path('detalleArticulo//<int:articulo_id>/', viewsDetalle.mostrarDetalle, name='detalle'),
  path('ordenarAlfabeticamente', viewsInicio.mostrarArticulosOrdenados, name='ordenados'),
  path('verOtroUsuario/<int:user_id>/', other_profile_views.view_other_profile, name= 'ver_otro_usuario'),
  path('eliminarCuenta/<int:user_id>/', eliminar_cuenta_views.delete_account, name='eliminar_cuenta'),
  path('listarEliminados', viewsInicio.mostrarArticulosAEliminar, name= 'listarAEliminar'),
  path('eliminarArticulo/<int:articulo_id>/', viewsInicio.eliminarArticulo, name='eliminarArticulo'), 
    path('verAyudantes/', ver_ayudantes,name = 'verAyudantes'),
    path('inicioAdmin/', viewsInicio.inicioAdmin ,name = 'inicioAdmin'),
    path('misArticulos/', ver_articulos, name='verArticulos'),
    path('verArticulos/<int:user_profile_id>/', other_profile_views.verProductos, name='productos_del_usuario'),
    path('articulos/', buscar_articulos, name='articulos'),
  #path('login/', autenticacion_views.login_view, name='login'),
 #path('perfil_propio/', perfil_views.view_profile, name='perfil_propio'),
 path('inicioAyudante/', viewsInicio.inicioAyudante, name='inicioAyudante'),
 path('marcar_leida/<int:notification_id>/', viewsInicio.marcar_leida, name='marcar_leida'),
 path('bloquear_usuario/<int:user_id>/', bloquear_usuario, name='bloquear_usuario'),
 path('usuarios/', lista_usuarios, name='lista_usuarios'), 
  path('agregarANeedList/<int:articulo_id>/', needListViews.agregarArticuloANeedList, name= 'agregarANeedList'),
 path('verNeedList', needListViews.verArticulosEnLaNeedList, name='verNeedList'),
 path('borrarDeNeedList/<int:articulo_id>/', needListViews.borrarArticuloDeNeedList, name='borrarDeNeedList'),
 path('confirmar_eliminar_articulo/<int:articulo_id>/', needListViews.confirmar_eliminar_articulo, name='confirmar_eliminar_articulo'),
 path('solicitarIntercambio/<int:articulo_id>/', solicitar_intercambio, name='solicitar_intercambio'),
#  path('controlar_intercambio/<int:intercambio_id>', controlar_intercambio, name='controlar_intercambio'),
 path('listaIntercambiosSolicitantes/', viewsInicio.mostrarSolictudesIntercambios, name='lista_intercambios_solicitantes'),
 path('listaIntercambiosPropuestos/', viewsInicio.mostrarIntercambiosPropuestos, name='lista_intercambios_propuestos'),
 path('listaIntercambios/', viewsInicio.mostrarIntercambios, name='lista_intercambios'),
 path('', include('controlarIntercambio.urls')),
  path('', include('eliminarArticulo.urls')),
 path('listadoABloquear', pendienteBloqueo.verUsuariosParaBloquear, name='verABloquear' ),
 path('listadoBloqueados', pendienteBloqueo.verUsuariosBloqueados, name='verBloqueados' ),
 path('bloquearPorPublicacion/<int:articulo_id>/<int:user_id>/', controlar_publicacionViews.bloquearUsuarioPorPublicacion, name='bloquearUsuarioPorInadecuado'),
 path('confirmarBloqueo/<int:articulo_id>/<int:user_id>/', controlar_publicacionViews.confirmar_bloquear, name='confirmar'),
 path('confirmar_eliminar_ayudante/<int:user_id>', confirmar_eliminar_ayudante, name='confirmar_eliminar_ayudante'),
 path('verMisPublicacionesPendientes', mostrarArticulosPendientesPropios, name='verArticulosPendientesPropios'),
 path('', include('verArticulosRechazados.urls')),
 path('intercambiosDelDia', viewsInicio.mostrarIntercambiosDelDia, name='verIntercambiosDelDia'),
path('efectuarIntercambio/<str:codigo_intercambio>/', viewsInicio.efectuarIntercambio, name='efectuarIntercambio'),
path('', include('estadisticas.urls')),
path('listadoIntercambiosAyudante/', viewsInicio.mostrarIntercambiosAyudante, name='listadoIntercambiosAyudante'), 
path('', include('dejarReseña.urls')),
path('', include('verReseñas.urls')),
path('', include('realizarDonacion.urls')),
path('listadoIntercambiosAyudante/', viewsInicio.mostrarIntercambiosAyudante, name='listadoIntercambiosAyudante'),
path('confirmarBloqueo/<int:user_id>', viewsInicio.confirmarBloqueo, name='confirmar_bloqueo_usuario'),
path('/historial_intercambios/', viewsInicio.ver_historial_intercambios, name='historial_intercambios'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autenticacionIntercambiador/urls.py
from django.urls import path
from . import views

#urlpatterns = [
   # path('login/', views.login_view, name='login'),  # Ruta para el inicio de sesión
#]

logout/urls.py
from django.urls import path
from .views import logout_view

urlpatterns = [
    path('logout/', logout_view, name='logout'),
]

autenticacionIntercambiador/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, Group, Permission
from django.db import models
from django import forms

class IntercambiadorManager(BaseUserManager):
    def create_user(self, dni, password=None, **extra_fields):
        if not dni:
            raise ValueError("El DNI es obligatorio")
        user = self.model(dni=dni, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, dni, password=None, **extra_fields):
        user = self.create_user(dni, password, **extra_fields)
        user.is_admin = True
        user.save(using=self._db)
        return user

class Intercambiador(AbstractBaseUser):
    dni = models.CharField(max_length=10, unique=True)
    failed_login_attempts = models.IntegerField(default=0)
    is_locked = models.BooleanField(default=False)
    # Solución para evitar el conflicto en los accesores inversos
    groups = models.ManyToManyField(Group, related_name='intercambiador_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='intercambiador_user_permissions')

    # Campo para la imagen de perfil con ImageField
    profile_picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)

    USERNAME_FIELD = 'dni'

    objects = IntercambiadorManager()

    def int(self):
        return self.dni

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

class CustomUser(AbstractBaseUser):
    # Otros campos de tu modelo CustomUser

    # Solución para evitar el conflicto en los accesores inversos
    groups = models.ManyToManyField(Group, related_name='customuser_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_user_permissions')

autenticacionIntercambiador/forms.py
from django import forms

class LoginForm(forms.Form):
    dni = forms.CharField(max_length=10, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True,  label="Contraseña")

autenticacionIntercambiador/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from app.models import CustomUser
from .forms import LoginForm
import random
from django.contrib import messages

def mostrar(request):
    return render(request, 'menuPrincipal.html', {'user': CustomUser})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            dni = form.cleaned_data['dni']
            password = form.cleaned_data['password']

            # Verificar si el usuario existe
            if CustomUser.objects.filter(dni=dni).first() is not None:
                if (CustomUser.objects.get(dni=dni)).borrado==False:
                    user_instance = CustomUser.objects.get(dni=dni)
                
                    # Verificar si el usuario está bloqueado
                    if user_instance.is_blocked and user_instance.failed_login_attempts < 3:
                        error_message = f"Su cuenta está bloqueada. Motivo: {user_instance.motivo_bloqueo}"
                        return render(request, 'autenticacionIntercambiador/login.html', {'form': form, 'error_message': error_message})
                    elif user_instance.failed_login_attempts >= 3:
                        user_instance.is_blocked = True
                        user_instance.motivo_bloqueo = "Demasiados intentos de inicio de sesión fallidos."
                        user_instance.save()
                        messages.error(request, f"Su cuenta está bloqueada. Motivo: {user_instance.motivo_bloqueo}")
                        return redirect('change_password')

                # Autenticar al usuario
                    user = authenticate(request, username=dni, password=password)
                    if user is not None:
                        if user.roles != 'usuario':
                            error_message = 'No se encuentra habilitado para iniciar sesión por este medio. Elija la opción "Iniciar sesión como administrador o ayudante".'
                            return render(request, 'autenticacionIntercambiador/login.html', {'form': form, 'error_message': error_message})
                        user_instance.failed_login_attempts = 0
                        user_instance.save()
                        login(request, user)
                    
                        if user.passChange:
                            return redirect('change_desired_password')
                        return redirect('menuPrincipal')
                    else:
                    # Incrementar intentos fallidos si la autenticación falla
                        user_instance.failed_login_attempts += 1
                        user_instance.save()

                        if user_instance.failed_login_attempts >= 3:
                            user_instance.is_blocked = True
                            # temp_password = str(random.randint(100000, 999999))
                            # user_instance.set_password(temp_password)
                            user_instance.motivo_bloqueo = "Demasiados intentos de inicio de sesión fallidos."
                            user_instance.save()
                            # send_mail(
                            #     'Cuenta Bloqueada',
                            #     f'Su cuenta ha sido bloqueada. Use esta contraseña temporal para iniciar sesión: {temp_password}. Siga las instrucciones enviadas por correo para desbloquear su cuenta.',
                            #     'ingecaritas@gmail.com',
                            #     [user_instance.email],
                            #     fail_silently=False,
                            # )
                            messages.error(request, f"Su cuenta está bloqueada. Motivo: {user_instance.motivo_bloqueo}")
                            return redirect('change_password')
                        else:
                            error_message = "El usuario y/o la contraseña son incorrectos"
                    
                        return render(request, 'autenticacionIntercambiador/login.html', {'form': form, 'error_message': error_message})
            else:
                error_message = "El usuario y/o la contraseña son incorrectos"
                return render(request, 'autenticacionIntercambiador/login.html', {'form': form, 'error_message': error_message})
    else:            form = LoginForm()

    return render(request, 'autenticacionIntercambiador/login.html', {'form': form})

autenticacionIntercambiador/templates/autenticacionIntercambiador/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Caritas{% endblock %}</title>
    <!-- Enlace a los archivos CSS de Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block styles %}{% endblock %}
</head>
<body>
    <header>
        <!-- Barra de navegación de Bootstrap 5 -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Caritas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href={% url 'inicio' %}>Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Acerca de</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-4">
        <!-- Formulario de inicio de sesión -->
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_dni" class="form-label">DNI</label>
                {{ form.dni }}
            </div>
            <div class="mb-3">
                <label for="id_password" class="form-label">Contraseña</label>
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <!-- Pie de página -->
            <p class="text-muted">Derechos de autor © 2024 Caritas</p>
        </div>
    </footer>

    <!-- Enlace a los archivos JavaScript de Bootstrap 5 (al final del cuerpo) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

autenticacionIntercambiador/templates/autenticacionIntercambiador/login.html
{% extends 'base.html' %}

{% block title %}
    Inicio de Sesión
{% endblock %}

{% block content %}
    <div class="login-container ">
        <h2>Iniciar Sesión</h2>
        <form method="post" class="d-inline">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_dni" class="form-label">Usuario</label>
                {{ form.dni }}
            </div>
            <div class="mb-3">
                <label for="id_password" class="form-label">Contraseña</label>
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-primary d-inline">Iniciar sesión</button>
        </form>
        <form action="{% url 'change_password' %}" method="get" class="d-inline">
            <button type="submit" class="btn btn-primary d-inline">Solicitar cambio de contraseña</button>
            <a href="{% url 'inicio' %}" class="btn btn-primary">Cancelar</a>
        </form>
        <!-- Ejemplo de mensaje de error -->
        {% if error_message %}
            <div class="error-message">{{ error_message }}</div>
        {% endif %}
    </div>
{% endblock %}